### ISSUE TITLE
Issue while downloading

### ISSUE THREAD

**Issue by seba11998** [MrHaCkEr/Wuxiaworld-2-eBook#11]
I'm trying to download The Great Ruler from start to finish (Chapters 1 - 450). But it never makes it through the 10th chapter the script always freezes between chapters 3 and 8 and stays at a Not Responding state

**Comment by MrHaCkEr** [comment]
Try removing line 62, 208 and 212-213 from getify.py

**Comment by seba11998** [comment]
Thanks! I did that and it worked but tis solution wasn't perfect 'cause it didn't delete the temporary files. So I tried with diferent solutions and I realized that just by deleting the line 208 the problem was perfectly solved.

**Comment by seba11998** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "wuxiaworld2ebook.py", line 60, in button_press
    getify.download(bulk_list[x], str(s_chapter) + ".xhtml")
  File "C:\Users\Sebastian Ramos\Downloads\Wuxiaworld-2-eBook-master\getify.py", line 28, in download
    with urllib.request.urlopen(url) as response, open(file_name, 'wb') as out_file:
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by seba11998** [comment]
Everithing was ok until it reached the chapter 428. Then the script failed and printed this error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "wuxiaworld2ebook.py", line 60, in button_press
    getify.download(bulk_list[x], str(s_chapter) + ".xhtml")
  File "C:\Users\Sebastian Ramos\Downloads\Wuxiaworld-2-eBook-master\getify.py", line 28, in download
    with urllib.request.urlopen(url) as response, open(file_name, 'wb') as out_file:
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Sebastian Ramos\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by seba11998** [comment]
Everithing was ok until it reached the chapter 428. Then the script failed and printed this error:

Exception in Tkinter callback
Traceback (most recent call last):
File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\tkinter_init_.py", line 1699, in call
    return self.func(*args)
File "wuxiaworld2ebook.py", line 60, in button_press
    getify.download(bulk_list[x], str(s_chapter) + ".xhtml")
File "C:\Users\User\Downloads\Wuxiaworld-2-eBook-master\getify.py", line 28, in download
    with urllib.request.urlopen(url) as response, open(file_name, 'wb') as out_file:
File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by MrHaCkEr** [comment]
I know about this issue and will fix it within the next big update. For know just create the ebook until chapter 427 and create a new one after chapter 428.
This problem is caused because of inconsistent link structure on Wuxiaworld.

**Comment by seba11998** [comment]
OK, thanks
